name: Nameless
main: com.machentertainment.Nameless.Nameless
version: 1.1 Alpha
description: Lurk in the shadows, let crime be anonymous.
depend: [TagAPI]

commands:
    nameless:
      usage: /nameless <command>
      description: Hide in the shadows.